// Per-build identity.
//
// Generated by tools/make-blank-copy.py -- do not edit by hand.
//
// This copy is served from the same origin as the original, and browser
// storage is shared across an origin. A distinct APP_ID keeps the two sets of
// data completely separate, and LEGACY_KEYS is intentionally empty so this
// copy never adopts data written by the original build.

export const APP_ID = "brother";
export const APP_NAME = "Finance Tracker";

export const LEGACY_KEYS = {};

export const storageKey = (name) => `pft_${APP_ID}_${name}`;

export function readWithLegacy(name) {
  return localStorage.getItem(storageKey(name));
}
