// Blank starting data.
//
// Generated by tools/make-blank-copy.py -- do not edit by hand; edit app/ and
// re-run the script. Deliberately contains no real figures: a fresh install
// collects its own opening balance and first account through the setup screen.
export const SEED_DATA = {
  meta: {
    version: 1,
    openingBalance: 0,
    openingDate: "2026-01-01",
    currency: "UZS"
  },

  actuals: [],
  budget: [],

  // Empty on purpose: with no accounts, the app shows first-run setup.
  accounts: [],
  transfers: [],

  goals: {
    marriage: {
      fxRate: 12500,
      rows: [],
      reserveAnnualUSD: 0,
      savedSoFar: 0
    },
    home: {
      variants: [
        { "name": "Option 1", "sqm": 0, "pricePerSqmMlnUZS": 0, "initialPct": 0.2, "markupPct": 0.4, "months": 120 }
      ],
      savedSoFar: 0
    },
    umrah: {
      amountUSD: 0,
      people: 1,
      bufferUSD: 0,
      fxRate: 12500,
      savedSoFar: 0
    }
  },

  targets: {
    defs: [
      { "name": "Target1", "due": "2027-03-01" },
      { "name": "Target2", "due": "2027-06-01" },
      { "name": "Target3", "due": "2027-09-01" },
      { "name": "Target4", "due": "2027-12-01" }
    ],
    checkpoints: []
  },

  recurring: [],
  specifications: [],
  creditRating: [],

  balanceSheetExtra: {
    investments: 0,
    otherAssets: [],
    liabilities: []
  }
};
