#!/usr/bin/env python3
"""
Generates a blank copy of the finance app for another person.

The copy is a full duplicate of app/ with three things changed:
  1. seed.js  -- emptied, so none of the original owner's figures ship with it
  2. config.js-- a different APP_ID, so the two copies cannot read or overwrite
                 each other's browser storage when served from the same origin
  3. branding -- generic name in the manifest, page title and header

Re-run this after changing app/ to bring the copy back in sync:

    python3 tools/make-blank-copy.py
"""

import pathlib
import shutil
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "app"
DEST = ROOT / "brother"

APP_ID = "brother"
APP_NAME = "Finance Tracker"
CACHE_NAME = "blank-finance-v1"

BLANK_SEED = '''// Blank starting data.
//
// Generated by tools/make-blank-copy.py -- do not edit by hand; edit app/ and
// re-run the script. Deliberately contains no real figures: a fresh install
// collects its own opening balance and first account through the setup screen.
export const SEED_DATA = {
  meta: {
    version: 1,
    openingBalance: 0,
    openingDate: "2026-01-01",
    currency: "UZS"
  },

  actuals: [],
  budget: [],

  // Empty on purpose: with no accounts, the app shows first-run setup.
  accounts: [],
  transfers: [],

  goals: {
    marriage: {
      fxRate: 12500,
      rows: [],
      reserveAnnualUSD: 0,
      savedSoFar: 0
    },
    home: {
      variants: [
        { "name": "Option 1", "sqm": 0, "pricePerSqmMlnUZS": 0, "initialPct": 0.2, "markupPct": 0.4, "months": 120 }
      ],
      savedSoFar: 0
    },
    umrah: {
      amountUSD: 0,
      people: 1,
      bufferUSD: 0,
      fxRate: 12500,
      savedSoFar: 0
    }
  },

  targets: {
    defs: [
      { "name": "Target1", "due": "2027-03-01" },
      { "name": "Target2", "due": "2027-06-01" },
      { "name": "Target3", "due": "2027-09-01" },
      { "name": "Target4", "due": "2027-12-01" }
    ],
    checkpoints: []
  },

  recurring: [],
  specifications: [],
  creditRating: [],

  balanceSheetExtra: {
    investments: 0,
    otherAssets: [],
    liabilities: []
  }
};
'''

BLANK_CONFIG = f'''// Per-build identity.
//
// Generated by tools/make-blank-copy.py -- do not edit by hand.
//
// This copy is served from the same origin as the original, and browser
// storage is shared across an origin. A distinct APP_ID keeps the two sets of
// data completely separate, and LEGACY_KEYS is intentionally empty so this
// copy never adopts data written by the original build.

export const APP_ID = "{APP_ID}";
export const APP_NAME = "{APP_NAME}";

export const LEGACY_KEYS = {{}};

export const storageKey = (name) => `pft_${{APP_ID}}_${{name}}`;

export function readWithLegacy(name) {{
  return localStorage.getItem(storageKey(name));
}}
'''


def replace_once(path: pathlib.Path, old: str, new: str) -> None:
    text = path.read_text()
    if old not in text:
        sys.exit(f"Expected text not found in {path.relative_to(ROOT)}:\n  {old[:80]}")
    path.write_text(text.replace(old, new, 1))


def main() -> None:
    if not SRC.is_dir():
        sys.exit("app/ not found")

    if DEST.exists():
        shutil.rmtree(DEST)
    shutil.copytree(SRC, DEST)

    (DEST / "js" / "seed.js").write_text(BLANK_SEED)
    (DEST / "js" / "config.js").write_text(BLANK_CONFIG)

    # Its own service worker cache, or the two copies would evict each other.
    sw = DEST / "sw.js"
    line = sw.read_text().splitlines()[0]
    replace_once(sw, line, f'const CACHE_NAME = "{CACHE_NAME}";')

    manifest = DEST / "manifest.json"
    replace_once(manifest, '"name": "Dilmurod Finance Tracker"', f'"name": "{APP_NAME}"')
    replace_once(manifest, '"short_name": "Dilmurod"', '"short_name": "Finance"')

    index = DEST / "index.html"
    replace_once(index, "<title>Dilmurod Finance Tracker</title>", f"<title>{APP_NAME}</title>")
    replace_once(index, 'content="Dilmurod Finance"', f'content="{APP_NAME}"')
    replace_once(index, "<h1>💰 Dilmurod Finance</h1>", f"<h1>💰 {APP_NAME}</h1>")

    settings = DEST / "js" / "pages" / "settings.js"
    replace_once(settings, "Dilmurod Finance Tracker · installed as a PWA", f"{APP_NAME} · installed as a PWA")

    files = sum(1 for _ in DEST.rglob("*") if _.is_file())
    print(f"Wrote {DEST.relative_to(ROOT)}/ ({files} files) with a blank seed and APP_ID={APP_ID!r}")


if __name__ == "__main__":
    main()
