#!/usr/bin/env python3
"""
Builds a single self-contained copy of the Personal page.

app/personal.html is split the way the rest of the app is -- separate
stylesheets and ES modules -- which means it needs a web server to run. This
folds all of it into one file that can be downloaded, mailed to yourself or
dropped on a phone and opened on its own:

  * both stylesheets inlined into a <style> block
  * config.js, utils.js and personal.js concatenated into one classic <script>
    (not a module, so it also runs off file:// with no server)
  * the app icon inlined as a data: URI
  * the Finance/Personal switcher removed -- a lone file has nowhere to switch to
  * the service worker registration removed -- there is no sw.js beside it

Output: personal-standalone.html at the repo root.

Re-run this after changing app/personal.html, app/css/personal.css or
app/js/personal.js to bring the copy back in sync:

    python3 tools/make-standalone-personal.py
"""

import base64
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
APP = ROOT / "app"
OUT = ROOT / "personal-standalone.html"

# Order matters: personal.js runs on load, so what it depends on has to be
# defined above it.
MODULES = ["js/config.js", "js/utils.js", "js/personal.js"]
STYLES = ["css/style.css", "css/personal.css"]

BANNER = ("<!-- Generated by tools/make-standalone-personal.py -- do not edit by hand.\n"
          "     Edit app/personal.html, app/css/personal.css or app/js/personal.js\n"
          "     and re-run the script. -->\n")


def read(rel):
    return (APP / rel).read_text(encoding="utf-8")


def strip_module_syntax(source, name):
    """Turns one ES module into plain script body: no imports, no exports.

    Everything ends up in a single scope, so a name defined twice would have
    one definition silently win. That is checked for rather than assumed.
    """
    source = re.sub(r"^import\s+.*?;\s*$", "", source, flags=re.MULTILINE | re.DOTALL)
    source = re.sub(r"^export\s+(?=(const|let|var|function|class)\b)", "", source, flags=re.MULTILINE)
    if re.search(r"^\s*(import|export)\b", source, flags=re.MULTILINE):
        sys.exit(f"{name}: leftover import/export after stripping -- the bundle would not run.")
    return source.strip()


def top_level_names(source):
    return re.findall(r"^(?:const|let|var|function|class)\s+([A-Za-z_$][\w$]*)", source, flags=re.MULTILINE)


def build_script():
    parts, seen = [], {}
    for rel in MODULES:
        body = strip_module_syntax(read(rel), rel)
        for name in top_level_names(body):
            if name in seen:
                sys.exit(f"Name collision: {name} is declared in both {seen[name]} and {rel}.")
            seen[name] = rel
        parts.append(f"// ---- {rel} ----\n{body}")

    bundle = "\n\n".join(parts)
    # No sw.js ships beside a standalone file, so the registration is dead code.
    bundle = re.sub(r"\n// The finance app registers.*?\n}\s*$", "", bundle, flags=re.DOTALL)
    if "serviceWorker" in bundle:
        sys.exit("Service worker registration still present -- update the pattern in this script.")
    # One scope of its own, so nothing leaks into globals.
    return "(function () {\n" + bundle + "\n})();"


def main():
    html = read("personal.html")

    styles = "\n\n".join(f"/* ---- {rel} ---- */\n{read(rel)}" for rel in STYLES)
    icon = base64.b64encode((APP / "icons/icon-192.png").read_bytes()).decode("ascii")
    icon_uri = f"data:image/png;base64,{icon}"

    # Stylesheet links -> one inline block.
    html = re.sub(r'\n *<link rel="stylesheet"[^>]*>', "", html)
    html = html.replace("</head>", f"  <style>\n{styles}\n  </style>\n</head>", 1)

    # Icons -> inlined, so the file carries its own.
    html = re.sub(r'href="\./icons/icon-192\.png"', f'href="{icon_uri}"', html)

    # The page switcher points at a sibling page that a lone file does not have.
    html = re.sub(r'\n *<nav class="page-switch">.*?</nav>', "", html, flags=re.DOTALL)

    # Module script -> one inline classic script. Passed as a function so the
    # JS (full of backslashes in its regexes) is not read as a re template.
    script = "\n  <script>\n" + build_script() + "\n  </script>"
    html = re.sub(r'\n *<script type="module"[^>]*></script>', lambda _: script, html)
    if "src=" in html or "<link rel=\"stylesheet\"" in html:
        sys.exit("An external reference survived -- the file would not be self-contained.")

    html = html.replace("<!doctype html>\n", "<!doctype html>\n" + BANNER, 1)
    OUT.write_text(html, encoding="utf-8")
    print(f"Wrote {OUT.relative_to(ROOT)} ({OUT.stat().st_size / 1024:.0f} KB)")


if __name__ == "__main__":
    main()
